Update reporting_kernel_bugs.md
hust-open-atom-club/TranslateProject pull request #142
Opened 2024-07-31 15:28 UTC by Ecila01

2024-07-31 16:49 UTC, tttturtle-russ requested changes

2024-07-31 16:49 UTC, tttturtle-russ commented on sources/syzkaller/linux/reporting_kernel_bugs.md
> +3. 这些名单上的最长禁运期限 embargo 为5周。
和原文格式保持一致。（不确定的英文单词可以在翻译后用括号括起来，不要这样写）

2024-08-12 12:05 UTC, mudongliang commented on sources/syzkaller/linux/reporting_kernel_bugs.md
> +3. 这些名单上的最长禁运期限 embargo 为5周。
我们在proofread的时候处理这个小问题吧

2024-08-12 12:10 UTC, tttturtle-russ approved these changes

2024-08-12 12:10 UTC, merged