完成README.md的翻译
hust-open-atom-club/TranslateProject pull request #193
Opened 2024-08-27 17:10 UTC by Athanlaich

2024-08-29 15:02 UTC, mudongliang reviewed
目前review到”章节: 开源软件的简短历史“，请简单查看一下修改的位置，我将尽快更新后续的review

2024-08-29 15:02 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +我们每天都依赖许多标准，包括 **TCP/IP** （互联网通信的基础标准）、**HTTP**（万维网背后的协议）、**HTML**（网页作者用于格式化内容的语言）、**GSM**（世界大部分地区的手机通信标准）、**ODF**（用于不同文字处理器之间交换文档的开放文档格式）和**PDF**（用于生成打印准备文档的便携文档格式）。
`**PDF**` 左侧加上空格

2024-08-31 08:34 UTC, Athanlaich commented on sources/OSPO-101/module1/README.md
> +计算机软件指的是由作者编写的程序或固件。软件的作者可以是一个或多个人，也可能代表一个公司进行工作。程序以机器可读的格式在特定的计算机上运行，这种格式是通过将 “源代码” 转换为 “二进制格式” 来实现的。
这里已经是中文双引号了

2024-09-02 15:49 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +在20世纪60年代末，随着计算机操作系统和编译器技术的发展，构建有效软件的过程变得更加简便，这些软件能够在多种计算机平台上运行。这直接导致了只专注于软件开发的公司的兴起。1974年，软件获得了版权保护的权利，这为软件成为重要的商品铺平了道路，这些公司为了保护自己的软件产品进行了不懈的斗争。
改成“随着计算机操作系统和编译器技术的发展，构建有效跨平台软件的过程变得更加简便。”

2024-09-02 15:49 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +在20世纪60年代末，随着计算机操作系统和编译器技术的发展，构建有效软件的过程变得更加简便，这些软件能够在多种计算机平台上运行。这直接导致了只专注于软件开发的公司的兴起。1974年，软件获得了版权保护的权利，这为软件成为重要的商品铺平了道路，这些公司为了保护自己的软件产品进行了不懈的斗争。
“软件获得了版权保护的权利” -> "软件获得了版权保护"

2024-09-02 15:49 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +1970年代后期和1980年代初见证了仅分发机器可读代码而不提供相应的人类可读源码的趋势。1980年代初，麻省理工学院的研究员 Richard Stallman 开始了一个项目，编写后来成为 GNU 操作系统的内容（该系统后来启发了现在流行的 Linux 内核）。在此期间，他创立了自由软件基金会（Free Software Foundation），并撰写了[自由软件定义](https://en.
"1970年代后期和1980年代初" -> “十九世纪 70 年代末到 80 年代初”

2024-09-02 15:49 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +Christine Peterson 和其他支持 “开源” 的人试图在这里澄清“自由”的概念——明确表明源代码将对外开放以供检查、再分发和修改。随着越来越多的公司参与这些软件生态系统，开源软件的吸引力逐渐增强，很大程度上是因为 “自由” 软件没有像“专业”开发的软件那样被认为具有价值。事实上，优质的开源软件数量只在不断增加，而且其中许多是由专业人员开发的。
“优质的开源软件数量只在不断增加”，此处感觉要意译，比如“优质的开源软件数量一直在不断增加”

2024-09-02 15:49 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +在这里，主要考虑的是技术因素，包括更快更好的开发，更多的贡献者和审稿人，更容易的调试等。
这里不太适合用“审稿人”一次，这个一般是论文审稿，建议用“评论者”

2024-09-02 15:49 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +# 章节: 使用开源的原因
I am here

2024-09-02 15:49 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +了解我们在开源和开放标准方面的历史，可以让我们更好地评估未来我们需要走的方向。
可以让我们更好地评估未来我们需要走的方向 -> "可以让我们更好地评估未来要走的方向"

2024-09-02 15:49 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +此外，越来越多的思考围绕计算的伦理方面，以及它如何影响从许可、知识产权到协作模式的一切。
许可-> 许可证

2024-09-02 15:49 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +这里有太多开放标准无法一一列举，但您可以在[维基百科](https://en.wikipedia.org/wiki/Open_standard)上找到一个相当不错的列表。浏览这个列表，你会发现一些你可能知道的（TCP/IP, PDF），以及一些你可能依赖但不太了解的（HTML, USB）。
是不是在”以及一些你可能依赖但不太了解的“后面加上“开放标准”？否则感觉不太完整

2024-09-06 15:38 UTC, mudongliang requested changes

2024-09-06 15:38 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +在讨论了一些社区开发模式之后，让我们来看一下各种规模的企业选择开源作为宝贵的技术工具来解决实际问题的原因。
now that 翻译为既然吧？另外，本句话里面没有主语

2024-09-06 15:38 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +* 成本更低
成本更低 改成 低成本

2024-09-06 15:38 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +开源软件在加速软件开发周期方面发挥了重要作用。一个最显著的例子就是移动设备市场，我们看到主要的新产品在6到12个月的周期内发布。开源对于快速演化交付至关重要。
”我们看到“ 删除

2024-09-06 15:38 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +* 领先的开源项目以社区驱动的功能演进，而非收入驱动的管理决策为主。这种快速的决策方式（通常是一种[懒共识](http://community.apache.org/committers/lazyConsensus.html)）使项目能够非常迅速地整合新功能和修复问题。
不同于收入驱动，领先的开源项目通过社区驱动快速演进。

2024-09-06 15:38 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +* 由于广泛的社区测试，成熟的开源软件通常具有更高的质量。事实上，根据  [Forrester Research 的研究](https://fossbazaar.org/system/files/OpenSourceForTheNextGenerationOfEnterpriseIT.pdf)，软件质量在92%的情况下达到了或超出了预期。
事实上，[Forrester Research 研究](https://fossbazaar.org/system/files/OpenSourceForTheNextGenerationOfEnterpriseIT.pdf)表明，软件质量在92%的情况下达到了或超出了预期。

2024-09-06 15:38 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +* 最近的一项 [Red Hat 研究](https://www.redhat.com/cms/managed-files/rh-enterprise-open-source-report-detail-f21756-202002-en.pdf) 显示，开源软件的总体拥有成本比商业/闭源解决方案低30%。
改成“总体成本”是否可以？

2024-09-06 15:38 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +* 移动通信领域的惊人创新速度只有通过开源才能实现。尽管Android是主要例子，但即使是像苹果的 iOS 这样的闭源平台也主要使用了数百个开源软件库和组件构建。
Android 两边需要空格

2024-09-06 15:38 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +* 移动通信领域的惊人创新速度只有通过开源才能实现。尽管Android是主要例子，但即使是像苹果的 iOS 这样的闭源平台也主要使用了数百个开源软件库和组件构建。
largely 翻译为大量地

2024-09-06 15:38 UTC, mudongliang commented on sources/OSPO-101/module1/README.md
> +许多开源社区展示了快速演进，通过参与这些社区可以加速您自己的创新。开源的自下而上式优胜者治理机制将所有权和责任重新引导回开发团队。
“许多开源社区展示了快速演进，通过参与这些社区可以加速您自己的创新。”这句话翻译很奇怪，但是我还没想到怎么翻译？

2024-09-06 15:39 UTC, mudongliang commented
@Athanlaich 我终于审核完了。你看一下这些comments怎么解决

2024-09-09 12:46 UTC, merged