翻译“Building and installing AFL++”（INSTALL.md）
hust-open-atom-club/TranslateProject pull request #226
Opened 2024-10-12 17:00 UTC by JadeSnow7

2024-10-13 10:30 UTC, Hornos3 reviewed
Please see those suggestions below and optimize your translation thx

2024-10-13 10:30 UTC, Hornos3 commented on sources/aflplusplus/INSTALL_zh.md
> +macOS 支持 AFL++ 仪器<!--instrumentation-->使用的 SYSV 共享内存，但仅使用默认设置并不够。在构建之前，请运行所提供的脚本来完善默认设置：
"AFL++ 仪器" 应改为 "AFL++ 插桩"

2024-10-13 10:30 UTC, Hornos3 commented on sources/aflplusplus/INSTALL_zh.md
> +macOS 似乎不支持 QEMU 的用户仿真模式，因此black-box instrumentation mode (-Q) 将无法运行。不过，FRIDA mode (-O) 可在 x86 和 arm64 macOS 上运行。
"用户仿真模式" 最好直接写为 "user mode"，它表示非内核级别的ring 3特权级用户程序仿真；"black-box instrumentation mode" 可改为 "黑盒插桩模式"

2024-10-13 10:30 UTC, Hornos3 commented on sources/aflplusplus/INSTALL_zh.md
> +*注：**make distrib**将会同时构建FRIDA mod，QEMU mod和unicorn mod等。如果您只想要单独的AFL++，可以执行**make all**。如果您还想同时编译一些辅助工具但不需要纯二进制文件，就选择：*
三个"mod"改为"mode"

2024-10-14 01:32 UTC, mudongliang commented on sources/aflplusplus/INSTALL_zh.md
> +# 构建与安装AFL++
CI 提示，你好像把我们的头部metadata给删掉了，需要加回来，具体请参考我们的wiki

2024-10-14 01:33 UTC, mudongliang commented on sources/aflplusplus/INSTALL_zh.md
> +# 构建与安装AFL++
感觉貌似构建错误也是因为头部metadata被删除了，添加回来之后看看CI会不会依然报错

2024-10-20 13:06 UTC, tttturtle-russ requested changes
为什么这个commit只修改了项目依赖？

2024-11-14 08:47 UTC, Hornos3 commented
@JadeSnow7 最后一次修改貌似不正确，请再确认一下检查错误的原因，如果长时间不回复我们将关闭PR

2024-11-16 01:01 UTC, mudongliang commented
目前 INSTALL.md 已经被人翻译过了。背后的原因是，你没有按照翻译流程走，锁定你要翻译的文章，所以后面有同学去申请的时候就不会出现conflict，这样他一旦合并你就会出现conflict

2024-11-16 01:02 UTC, mudongliang commented
我个人建议你把 **WritingAnLLVMNewPMPass.md** 的翻译单独整理出来，按照翻译流程进行翻译

2024-11-16 03:31 UTC, mudongliang commented
@JadeSnow7 建议你重新做一个只有llvm文件的pr，这个pr里面已经很乱了。你自己可以看一下自己pr的修改文件

2024-11-16 03:36 UTC, closed without merging

2024-11-20 09:39 UTC, mudongliang commented
@JadeSnow7 如果你准备翻译 WritingAnLLVMNewPMPass.md 的话，建议你先按照本仓库 Wiki 先申请翻译，否则还会出现翻译被人做过的情况出现

2024-11-20 09:48 UTC, mudongliang commented
你看看最新的HCTT仓库，现在的状态还是collected，不是translating