申领对WritingAnLLVMNewPMPass.md的翻译
hust-open-atom-club/TranslateProject pull request #239
Opened 2024-11-21 10:48 UTC by JadeSnow7

2024-11-21 11:58 UTC, mudongliang commented on sources/llvm/WritingAnLLVMNewPMPass.md
> +status: translating
我看你已经把翻译都放上来了，所以建议你直接修改status为translate

2024-11-21 11:59 UTC, mudongliang commented on sources/llvm/WritingAnLLVMNewPMPass.md
> +translating_date: 20241116
那这样也要改成translated_date

2024-11-21 12:00 UTC, mudongliang commented on sources/llvm/WritingAnLLVMNewPMPass.md
> +`NewPassManager`.
这是英文句号

2024-11-21 12:00 UTC, mudongliang commented on sources/llvm/WritingAnLLVMNewPMPass.md
> +本文介绍了新的pass管理机制（New Pass Manager，NPM）。LLVM对代码生成管道使用的是传统的pass管理机制（Legacy Pass Manager）。详情参阅
英文两边如果是中文要加空格分割

2024-11-21 12:00 UTC, mudongliang commented on sources/llvm/WritingAnLLVMNewPMPass.md
> +# 编写LLVM Pass
英文两边如果是中文要加空格分割

2024-11-21 12:01 UTC, mudongliang commented on sources/llvm/WritingAnLLVMNewPMPass.md
> +LLVM pass框架是LLVM系统中一个非常重要的组成部分，因为大多数编译器最值得关注的部分都在LLVM pass上。Pass执行着编译器的各种转换和优化工作，它们提供这些转换工作所需要的分析结果，并且最重要的是，它们为编译器代码提供了一种组织技术。
英文两边如果是中文要加空格分割。请全文进行检测，如果两边是其他符号，可以参考Wiki 中的中文翻译指北来确认

2024-11-22 16:11 UTC, tttturtle-russ requested changes

2024-11-22 16:11 UTC, tttturtle-russ commented on sources/llvm/WritingAnLLVMNewPMPass.md
> +在 `llvm/lib/Passes/PassBuilder.cpp` 中包含头文件
由于不同的原因，`llvm/lib/Passes/PassBuilder.cpp` 包含了多次 `llvm/lib/Passes/PassRegistry.def`。由于其负责构建我们的 pass，所以我们也需要在 `llvm/lib/Passes/PassBuilder.cpp` 包含正确的头文件。

2024-11-22 16:11 UTC, tttturtle-russ commented on sources/llvm/WritingAnLLVMNewPMPass.md
> +- extern "C" ::llvm::PassPluginLibraryInfo llvmGetPassPluginInfo() LLVM_ATTRIBUTE_WEAK;
与原文格式一致

2024-12-05 01:59 UTC, tttturtle-russ commented
Any update?

2025-02-17 07:44 UTC, closed without merging

2025-02-17 07:45 UTC, mudongliang commented
@tttturtle-russ 感觉这种情况可以使用 CI 进行统一处理？

2025-02-17 09:56 UTC, tttturtle-russ commented
> @tttturtle-russ 感觉这种情况可以使用 CI 进行统一处理？

同意