feat(lint): lint all Markdown files
hust-open-atom-club/TranslateProject pull request #243
Opened 2024-11-25 17:46 UTC by inscripoem

#240 

This workflow allows for manual triggering and checks all Markdown files in the repository for linting issues, providing reports and suggested fixes for any errors found. It will generate an artifact with zhlint log and autofix files

Test run:

- [Lint All #1](https://github.com/inscripoem/TranslateProject/actions/runs/12015369541) in inscripoem/TranslateProject

There might be still a bug in `zhlint` package which will cause failed linting for some articles. But we can check other articles before it is fixed.

2024-11-25 17:51 UTC, inscripoem commented
The test run shows that there are at least 92 articles waiting to be fixed. And after roughly proofreading, I'm afraid autofixes are not working for some articles because they have problems including flipped quotation marks or missing period which me may not need.

2024-11-28 07:46 UTC, mudongliang commented
https://github.com/hust-open-atom-club/hust-mirrors/commit/eb1a52e97362b2d5c86867397325d68cbf4af4a4

参考上述内容添加配置文件，处理半角全角的问题

2024-11-28 07:47 UTC, mudongliang requested changes
https://github.com/hust-open-atom-club/hust-mirrors/commit/eb1a52e97362b2d5c86867397325d68cbf4af4a4

2024-12-17 11:13 UTC, mudongliang approved these changes

2024-12-17 11:13 UTC, merged